In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_raw = pd.read_csv('../data/sentimentdataset.csv')
df_raw.head(-10)

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,718,722,Participating in a debate club to enhance crit...,Neutral,2023-10-15 20:45:00,DebateClubParticipationHighSchool,Twitter,#DebateSkills #HighSchoolIntellect,22.0,43.0,Canada,2023,10,15,20
718,719,723,Celebrating a friend's birthday with a surpris...,Happy,2023-10-16 15:45:00,BirthdaySurpriseHighSchool,Instagram,#SurpriseParty #HighSchoolCelebration,27.0,52.0,UK,2023,10,16,15
719,720,724,Successfully completing a challenging coding p...,Happy,2023-10-17 12:30:00,CodingSuccessHighSchool,Twitter,#CodingTriumph #HighSchoolTech,24.0,48.0,USA,2023,10,17,12
720,721,725,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19.0,38.0,Canada,2023,10,18,16
721,722,726,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21.0,42.0,UK,2023,10,19,18

In [3]:
positive = {
    "positive", "happiness", "joy", "love", "amusement", "enjoyment",
    "admiration", "affection", "awe", "acceptance", "adoration",
    "anticipation", "calmness", "excitement", "kind", "pride",
    "elation", "euphoria", "contentment", "serenity", "gratitude",
    "hope", "empowerment", "compassion", "tenderness", "enthusiasm",
    "fulfillment", "reverence", "zest", "hopeful", "proud",
    "grateful", "empathetic", "compassionate", "playful",
    "free-spirited", "inspired", "confident", "determination",
    "thrill", "overjoyed", "inspiration", "motivation",
    "satisfaction", "blessed", "appreciation", "confidence",
    "accomplishment", "wonderment", "optimism", "enchantment",
    "harmony", "creativity", "radiance", "wonder",
    "rejuvenation", "coziness", "adventure", "freedom",
    "dazzle", "resilience", "spark", "marvel", "friendship",
    "success", "amazement", "romance", "captivation",
    "tranquility", "grandeur", "celebration", "charm",
    "ecstasy", "connection", "iconic", "engagement",
    "touched", "triumph", "heartwarming", "solace",
    "breakthrough", "relief", "happy"
}

negative = {
    "negative", "anger", "fear", "sadness", "disgust",
    "disappointed", "bitter", "confusion", "shame",
    "despair", "grief", "loneliness", "jealousy",
    "resentment", "frustration", "boredom", "anxiety",
    "intimidation", "helplessness", "envy", "regret",
    "melancholy", "bitterness", "yearning", "fearful",
    "apprehensive", "overwhelmed", "jealous",
    "devastated", "frustrated", "envious", "dismissive",
    "heartbreak", "betrayal", "suffering",
    "emotionalstorm", "isolation", "disappointment",
    "lostlove", "exhaustion", "sorrow", "darkness",
    "desperation", "ruins", "desolation", "loss",
    "heartache", "obstacle", "pressure",
    "miscalculation", "challenge", "embarrassed",
    "sad", "hate", "bad"
}

neutral = {
    "neutral", "curiosity", "indifference", "numbness",
    "nostalgia", "ambivalence", "contemplation",
    "reflection", "mindfulness", "pensive",
    "immersion", "suspense", "emotion",
    "energy", "journey", "exploration",
    "imagination"
}

In [4]:
import pandas as pd

# Exemplo: coluna contendo os sentimentos
# df = pd.read_csv("dados.csv")

def normalize_sentiment(sentiment):
    s = sentiment.strip().lower()

    if s in positive:
        return "positive"
    elif s in negative:
        return "negative"
    elif s in neutral:
        return "neutral"
    else:
        return "neutral"  # fallback padrão

# Aplicação
df_raw["sentiment_3class"] = df_raw["Sentiment"].apply(normalize_sentiment)

print(df_raw[["Sentiment", "sentiment_3class"]].head())

     Sentiment sentiment_3class
0   Positive           positive
1   Negative           negative
2   Positive           positive
3   Positive           positive
4   Neutral             neutral

In [9]:
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(
    "vinai/bertweet-base"
)

model = AutoModelForSequenceClassification.from_pretrained(
    "vinai/bertweet-base",
    num_labels=3
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
[transformers] emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0
Loading weights: 100%|██████████| 197/197 [00:00<00:00, 5188.72it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/bertweet-base
Key                         | Status     |
----------------------------+------------+-
lm_head.decoder.bias        | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.decoder.weight      | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [10]:
label_map = {
    "negative": 0,
    "neutral": 1,
    "positive": 2
}

df_raw["label"] = df_raw["sentiment_3class"].map(label_map)

In [11]:
from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df_raw["Text"].tolist(),
    df_raw["label"].tolist(),
    test_size=0.2,
    random_state=42
)

In [12]:
train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128
)

In [13]:
import torch

class SentimentDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(self.labels[idx])

        return item

    def __len__(self):
        return len(self.labels)

In [14]:
train_dataset = SentimentDataset(
    train_encodings,
    train_labels
)

test_dataset = SentimentDataset(
    test_encodings,
    test_labels
)

In [15]:
from sklearn.metrics import accuracy_score, f1_score
import numpy as np

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    return {
        "accuracy": accuracy_score(labels, predictions),
        "f1": f1_score(labels, predictions, average="weighted")
    }

In [16]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs"
)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [17]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

In [18]:
#trainer.train()

In [19]:
# model.save_pretrained("./roberta_sentiment")

# tokenizer.save_pretrained("./roberta_sentiment")

#Load the pretrained model and tokenizer
model = AutoModelForSequenceClassification.from_pretrained("./roberta_sentiment")
tokenizer = AutoTokenizer.from_pretrained("./roberta_sentiment")

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 1339.33it/s]
[transformers] emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0

In [20]:
results = trainer.evaluate()

print(results)

c:\Users\Gabri\Desktop\UFMG\2026-1\Causal\TPFinal\causal-learning-sentiment-analysis\.venv\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 1.081934928894043, 'eval_accuracy': 0.5170068027210885, 'eval_f1': 0.35239925566639213}

In [21]:
text = "The food was definitely good, but when all was said and done, I just couldn't justify it for the price"

inputs = tokenizer(
    text,
    return_tensors="pt"
)

outputs = model(**inputs)

prediction = outputs.logits.argmax(dim=1)

print(prediction)

tensor([0])

In [22]:
df_raw.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,sentiment_3class,label
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12,positive,2
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8,negative,0
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15,positive,2
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18,positive,2
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19,neutral,1

In [23]:
import nlpaug.augmenter.word as naw

aug = naw.SynonymAug()

text = "excellent service crashing again"

augmented = aug.augment(text)

print(augmented)

['splendid service crashing once more']

In [24]:
# counterfactual_pairs = []
original_text = []
augmented_text = []


for text in df_raw["Text"].tolist()[:100]:

    augmented = aug.augment(text)

    original_text.append(text)
    augmented_text.append(augmented)

In [25]:
inputs_original = tokenizer(
    original_text,
    return_tensors="pt",
    truncation=True,
    padding=True
)

inputs_augmented = tokenizer(
    augmented_text,
    return_tensors="pt",
    truncation=True,
    padding=True
)

In [26]:
import torch.nn.functional as F


outputs_original = model(**inputs_original)

outputs_augmented = model(**inputs_augmented)

# logits_original = outputs_original.logits

# logits_augmented = outputs_augmented.logits

# loss_ce = criterion(
#     logits_original,
#     labels
# )

# loss_consistency = F.mse_loss(
#     logits_original,
#     logits_augmented
# )

# loss = loss_ce + 0.2 * loss_consistency

: