In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_raw = pd.read_csv('../data/sentimentdataset.csv')
df_raw.head(-10)

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,718,722,Participating in a debate club to enhance crit...,Neutral,2023-10-15 20:45:00,DebateClubParticipationHighSchool,Twitter,#DebateSkills #HighSchoolIntellect,22.0,43.0,Canada,2023,10,15,20
718,719,723,Celebrating a friend's birthday with a surpris...,Happy,2023-10-16 15:45:00,BirthdaySurpriseHighSchool,Instagram,#SurpriseParty #HighSchoolCelebration,27.0,52.0,UK,2023,10,16,15
719,720,724,Successfully completing a challenging coding p...,Happy,2023-10-17 12:30:00,CodingSuccessHighSchool,Twitter,#CodingTriumph #HighSchoolTech,24.0,48.0,USA,2023,10,17,12
720,721,725,Attending a school talent show to support clas...,Happy,2023-10-18 16:45:00,TalentShowSupportHighSchool,Facebook,#TalentShow #HighSchoolEntertainment,19.0,38.0,Canada,2023,10,18,16
721,722,726,Exploring a new hiking trail with friends over...,Happy,2023-10-19 18:20:00,WeekendHikeHighSchool,Instagram,#NatureAdventures #HighSchoolFriends,21.0,42.0,UK,2023,10,19,18

In [13]:
positive = {
    "positive", "happiness", "joy", "love", "amusement", "enjoyment",
    "admiration", "affection", "awe", "acceptance", "adoration",
    "anticipation", "calmness", "excitement", "kind", "pride",
    "elation", "euphoria", "contentment", "serenity", "gratitude",
    "hope", "empowerment", "compassion", "tenderness", "enthusiasm",
    "fulfillment", "reverence", "zest", "hopeful", "proud",
    "grateful", "empathetic", "compassionate", "playful",
    "free-spirited", "inspired", "confident", "determination",
    "thrill", "overjoyed", "inspiration", "motivation",
    "satisfaction", "blessed", "appreciation", "confidence",
    "accomplishment", "wonderment", "optimism", "enchantment",
    "harmony", "creativity", "radiance", "wonder",
    "rejuvenation", "coziness", "adventure", "freedom",
    "dazzle", "resilience", "spark", "marvel", "friendship",
    "success", "amazement", "romance", "captivation",
    "tranquility", "grandeur", "celebration", "charm",
    "ecstasy", "connection", "iconic", "engagement",
    "touched", "triumph", "heartwarming", "solace",
    "breakthrough", "relief", "happy"
}

negative = {
    "negative", "anger", "fear", "sadness", "disgust",
    "disappointed", "bitter", "confusion", "shame",
    "despair", "grief", "loneliness", "jealousy",
    "resentment", "frustration", "boredom", "anxiety",
    "intimidation", "helplessness", "envy", "regret",
    "melancholy", "bitterness", "yearning", "fearful",
    "apprehensive", "overwhelmed", "jealous",
    "devastated", "frustrated", "envious", "dismissive",
    "heartbreak", "betrayal", "suffering",
    "emotionalstorm", "isolation", "disappointment",
    "lostlove", "exhaustion", "sorrow", "darkness",
    "desperation", "ruins", "desolation", "loss",
    "heartache", "obstacle", "pressure",
    "miscalculation", "challenge", "embarrassed",
    "sad", "hate", "bad"
}

neutral = {
    "neutral", "curiosity", "indifference", "numbness",
    "nostalgia", "ambivalence", "contemplation",
    "reflection", "mindfulness", "pensive",
    "immersion", "suspense", "emotion",
    "energy", "journey", "exploration",
    "imagination"
}

In [14]:
import pandas as pd

# Exemplo: coluna contendo os sentimentos
# df = pd.read_csv("dados.csv")

def normalize_sentiment(sentiment):
    s = sentiment.strip().lower()

    if s in positive:
        return "positive"
    elif s in negative:
        return "negative"
    elif s in neutral:
        return "neutral"
    else:
        return "neutral"  # fallback padrão

# Aplicação
df_raw["sentiment_3class"] = df_raw["Sentiment"].apply(normalize_sentiment)

print(df_raw[["Sentiment", "sentiment_3class"]].head())

     Sentiment sentiment_3class
0   Positive           positive
1   Negative           negative
2   Positive           positive
3   Positive           positive
4   Neutral             neutral

In [15]:
df_raw

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,sentiment_3class
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12,positive
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8,negative
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15,positive
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18,positive
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,728,732,Collaborating on a science project that receiv...,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20.0,39.0,UK,2017,8,18,18,positive
728,729,733,Attending a surprise birthday party organized ...,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25.0,48.0,USA,2018,6,22,14,positive
729,730,734,Successfully fundraising for a school charity ...,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22.0,42.0,Canada,2019,4,5,17,positive
730,731,735,"Participating in a multicultural festival, cel...",Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21.0,43.0,UK,2020,2,29,20,positive
731,732,736,Organizing a virtual talent show during challe...,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24.0,47.0,USA,2020,11,15,15,positive